POST http://localhost:3333/create-user
Content-Type: application/json

{
    "email": "robin.nico@email.com",
    "password": "password"
}


###

POST http://localhost:3333/login
Content-Type: application/json

{
    "email": "email2@dominio.com",
    "password": "password"
}


###


@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAyIiwiaWF0IjoxNzgwOTY3ODc2LCJleHAiOjE3ODA5Njc4OTF9.j-lOVf6qlI9EWxGE8PlgyuYcGHo9wHpf7Evos5v6UbY
GET http://localhost:3333/profile?email="email@dominio.com"
Content-Type: application/json
Authorization: Bearer {{token}}